node_prefix = "win-node"
bind_host = "0.0.0.0"
bind_port = 50052
log_level = "debug"
data_dir = "E:\\librorum\\data"
heartbeat_interval = 5
discovery_interval = 10
# 添加已知节点
known_nodes = [
    "gy.local:50051",
    "192.168.31.90:50051", 
    "192.168.31.91:50051",
    "127.0.0.1:50052"
] 